app.port=${APP_PORT:8080}
app.token.secret=${APP_TOKEN_SECRET:change-me-in-production}
app.token.ttl.minutes=${APP_TOKEN_TTL_MINUTES:60}
app.otp.default.length=${APP_OTP_DEFAULT_LENGTH:6}
app.otp.default.ttl.seconds=${APP_OTP_DEFAULT_TTL_SECONDS:300}
app.otp.scheduler.fixed.delay.seconds=${APP_OTP_SCHEDULER_FIXED_DELAY_SECONDS:30}
app.file.otp.path=${APP_FILE_OTP_PATH:otp-codes}

app.db.url=${APP_DB_URL:jdbc:postgresql://localhost:5433/security_token_db}
app.db.user=${APP_DB_USER:postgres}
app.db.password=${APP_DB_PASSWORD:postgres}

app.email.resource=email.properties
app.sms.resource=sms.properties
app.telegram.resource=telegram.properties
